### ISSUE TITLE
onChange event for this slider?

### ISSUE THREAD

**Issue by anurag6792** [stofolus/angular-range-slider#10]
Please provide the documentation of using this slider.

**Comment by stofolus** [comment]
There is no onChange event. If this is something you would like feel free to create a PR.

There is documentation on how to use it in 
https://github.com/stofolus/angular-range-slider/blob/master/README.md 

and an example where it works in
https://github.com/stofolus/angular-range-slider/blob/master/examples/index.html

**Comment by anurag6792** [comment]
@stofolus : can you tell me a way to detect changes in the model value.? I'm using $watch , but it is not working properly.

**Comment by anurag6792** [comment]
@stofolus  : tapping out of the track is also moving the thumb and changing model value, in mobile devices and browser.

**Comment by stofolus** [comment]
I can look into using a watch later. It should work but I'll try it out.

Are you experiencing the bugs on mobile on http://codepen.io/stofolus/pen/NxrmyM ?
What device and OS are you using?

**Comment by anurag6792** [comment]
Yes on mobile devices. What i found is that...after changing range..when I click outside ...the range again changes in the direction i'have clicked

**Comment by stofolus** [comment]
Are you clicking just outside or is it far?

Here is a working example with a watch:
http://codepen.io/stofolus/pen/grNNYY

**Comment by anurag6792** [comment]
clicking/tapping anywhere outside is resulting in the same behaviour.

**Comment by stofolus** [comment]
I have tried now with both android and iPhone devices and it doesn't happen to me. The only time that this should happen is if you have made the slider larger using css. What exakt devices are you using? Can you record when it happens on the codepen.io link

**Comment by anurag6792** [comment]
I have changed the dimensions of the slider.I have made it smaller. Is that a issue?

**Comment by stofolus** [comment]
The problem may be that you have only changed the inner part. Not the entire slider. You need to make the surrounding elements smaller as well

**Comment by anurag6792** [comment]
But if I change the <slider> tags css i.e. reduce its width to like 50%...everything inside it should be contained within it , right? It should not affect the inner elements

**Comment by stofolus** [comment]
The best way is to use the scss file. Otherwise you need to look at how the scss variables are applied

**Comment by anurag6792** [comment]
ok I will try.. BTW this is a great slider..which works on all platform

**Comment by stofolus** [comment]
I'm closing this since I can't recreate your bug and it's probably because you've changed the styling.

If you continue to experience problems go ahead and open a new issue with a link to a codepen or jsfiddle example that recreates the issue
